# inventory/group_vars/all.yml — Chapter 3
---
ansible_user: ansible
ansible_python_interpreter: /usr/bin/python3
baseline_ntp_servers:
  - ntp1.company.com
  - ntp2.company.com
  - 0.rhel.pool.ntp.org
