# inventory/hosts.yml — Chapter 3
---
all:
  children:
    production:
      children:
        prod_web:
          hosts:
            web[01:10].prod.company.com:
        prod_db:
          hosts:
            db[01:04].prod.company.com:
        prod_app:
          hosts:
            app[01:20].prod.company.com:
    staging:
      children:
        stg_web:
        stg_db:
    lab:
      hosts:
        node01:
          ansible_host: 192.168.1.11
        node02:
          ansible_host: 192.168.1.12
        node03:
          ansible_host: 192.168.1.13
