# =============================================================================
# Ansible Inventory — Auto-generated by Terraform
# The Ansible AIOps Playbook (Apress) — Chapter 1 Lab
# GitHub: https://github.com/balaramaa/ansible-aiops-playbook
#
# DO NOT EDIT — regenerated on every `terraform apply`
# =============================================================================

[control]
control ansible_host=${control_ip} ansible_user=rocky ansible_ssh_private_key_file=${key_file}

[managed]
%{ for i, ip in managed_ips ~}
${managed_names[i]} ansible_host=${ip} ansible_user=rocky ansible_ssh_private_key_file=${key_file}
%{ endfor ~}

[lab:children]
control
managed

[lab:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

# ── Group vars for book chapters ──────────────────────────────────────────────
# Override these in group_vars/ as chapters progress
[managed:vars]
book_repo=https://github.com/balaramaa/ansible-aiops-playbook
lab_environment=aws
